### ISSUE TITLE
콘솔에 출력되는 SQL, Parameter, ResultSet을 한꺼번에 보여준다.

### ISSUE THREAD

**Issue by devsejong** [JAVACAFE-STUDY/loggable-datasource#2]
SQL과 Parameter는 query가 호출될 때 로그가 출력되며
ResultSet은 ResultSet이 닫힐때 로그가 출력되고 있다.

SQL과 ResultSet모두 한번에 보이도록 처리하자

**Comment by redrebel** [comment]
한번에 보이도록하는건 고려사항이 좀 있을것 같습니다.

1. SQL 문은 보인다는 것은 DB 로 전달되는 SQL문을 확인하기 위해 사용되는 것입니다. 
만일 SQL 문 자체가 잘못되었을 경우나 다른 경우에서도 보여줘야 된다는것이 원칙이라고 하면 
결국 DB 로 전달되기 전에 보여지는것이 좋을것 같습니다.

2. ResultSet을 보여주는 부분을 close() 두는 것보다 차라리 toString() 을 오버로딩해서 logger 로 넘길때
resultSet을 print 할수있게 하는건 어쩔지....

**Comment by devsejong** [comment]
에러가 발생하는 상황에서도 정상적으로 Log와 파라미터를 볼 수 있어야 한다.
각 메서드마다 try/catch문을 넣은다음 에러발생시에도 로그가 찍히도록 처리한다.
